version: "3"
services:
  main:
    image: sm30
    build:
      dockerfile: Dockerfile
      context: .
    runtime: nvidia
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"