version: "2.3"
services:
  main:
    image: sm30:$USER
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
      args:
        USERNAME: $USER
    runtime: nvidia
    volumes:
      - ${HOME}/.aws:${HOME}/.aws:ro
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - /opt/dvc/cache:/opt/dvc/cache
      - ..:/workspace
    environment:
      - TOKENIZERS_PARALLELISM=true
      - WANDB_CONSOLE=off
    command: /bin/sh -c "while sleep 1000; do :; done"
